server:
  port: 8761

spring:
  application:
    name: eureka-server #服务名称

eureka:
  server:
    enable-self-preservation: true #自我保护机制
    eviction-interval-timer-in-ms: 10000  #清理间隔30秒
  instance:
    hostname: eureka1 #节点
    prefer-ip-address: true #获取本机ip
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #向注册中心注册ip:端口号
  client:
    healthcheck:
      enabled: true   #改变eureka server对客户端健康检查方式
    register-with-eureka: false   #是否将自己注册到注册中心
    fetch-registry: true   #是否可检索
    #service-url:
      #defaultZone: http://localhost:8762/eureka/
        ####################################################
        # 搭建高可用需配置eureka.instance.hostname: 注册中心host文件名称
        # 单机在修改本地C:\Windows\System32\drivers\etc\hosts 如：127.0.0.1     server2
        #127.0.0.1     server3
        # 集群则无需此操作

      #enable-self-preservation: false    自我保护机制，生产环境建议开启
        #1、Eureka Server不再从注册列表中移除因为长时间没收到心跳而应该过期的服务。
      #
      #2、Eureka Server仍然能够接受新服务的注册和查询请求，但是不会被同步到其它节点上，保证当前节点依然可用。
      #
      #3、当网络稳定时，当前Eureka Server新的注册信息会被同步到其它节点中。
        ####################################################