#本地配置
server:
  port: 8200

spring:
  application:
    name: config-server
  profiles:
    active: native #表示读取本地
  cloud:
    config:
      server:
        #################git#################
        git:
          uri: https://github.com/peichuanjiang/spring-cloud-demo.git
          username: 269816847@qq.com
          password: 1565674986pei
        #####################################
        ##############读本地配置#############
        #native:
          #searchLocations: D:/ #文件地址在d盘,启动项目访问：http://localhost:8100/文件名,文件名yml格式:port: 8001
        ######################################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


